Added custom rules
pqrs-org/KE-complex_modifications pull request #1148
Opened 2022-06-24 15:08 UTC by Namu-Lee

1. IME: Caps Lock to ctrl+shift+space
2. Modifier+Backsapce to Delete
3. right option+arrow to pageup/pagedown/home/end

2022-06-24 15:16 UTC, MuhammedZakir commented
Can you please format the json files and also update the branch?

2022-06-24 15:44 UTC, Namu-Lee commented
done!

2022-06-24 15:58 UTC, MuhammedZakir requested changes

2022-06-24 15:58 UTC, MuhammedZakir commented on public/json/backspace_to_delete.json
> +					 "repeat":true,
Please remove this. `repeat` is `true` by default.

2022-06-24 15:58 UTC, MuhammedZakir commented on public/json/backspace_to_delete.json
> +					 "repeat":true,
This too.

2022-06-24 15:59 UTC, MuhammedZakir commented
Other than those 2, everything else is okay. Thank you!

2022-06-24 18:08 UTC, Namu-Lee commented
Removed all "repeat: true". thanks.

2022-06-25 03:54 UTC, MuhammedZakir commented on public/json/option+arrow_to_pagecontrol.json
> +			  "modifiers": []
```suggestion
			  "key_code": "page_up"
```

2022-06-25 03:54 UTC, MuhammedZakir commented on public/json/option+arrow_to_pagecontrol.json
> +			  "modifiers": []
```suggestion
			  "key_code": "page_down"
```

2022-06-25 03:55 UTC, MuhammedZakir commented on public/json/option+arrow_to_pagecontrol.json
> +			  "modifiers": []
```suggestion
			  "key_code": "home"
```

2022-06-25 03:55 UTC, MuhammedZakir commented on public/json/option+arrow_to_pagecontrol.json
> +			  "modifiers": []
```suggestion
			  "key_code": "end"
```

2022-06-25 03:57 UTC, MuhammedZakir commented
There was also a blank `to.modifiers`. That is also not needed. I have removed that myself.

2022-06-25 03:58 UTC, MuhammedZakir approved these changes

2022-06-25 04:00 UTC, merged

2022-06-25 04:01 UTC, MuhammedZakir commented
Merged. :-)