Add public/json/printscreen_command+shift+5.json
pqrs-org/KE-complex_modifications pull request #1191
Opened 2022-08-16 13:45 UTC by herryyu

Simply map PrintScreen key on windows keyboard to macOS's command+shift+5 shortcut.

2022-08-16 15:46 UTC, MuhammedZakir requested changes

2022-08-16 15:46 UTC, MuhammedZakir commented on public/groups.json
> +        },
Can you please move this to "Os Functionality" category? It's better suited IMHO.

2022-08-16 15:46 UTC, MuhammedZakir commented on public/json/printscreen_command+shift+5.json
> +            "key_code": "print_screen"
```suggestion
            "key_code": "print_screen",
            "modifiers": {
              "optional": [ "caps_lock" ]
            }
```

This is optional; add it if you are okay with this.

2022-08-17 07:31 UTC, herryyu commented on public/groups.json
> +        },
NO problem :)

2022-08-26 02:26 UTC, MuhammedZakir approved these changes

2022-08-26 02:27 UTC, merged