new keyset add request
pqrs-org/KE-complex_modifications pull request #768
Opened 2020-11-02 06:29 UTC by rationality6

Hello.
I want to upload to the public my mod keyset.
Let me know If there is something to change.
This is my first time to upload my keyset to the public so
Thank you.

2020-11-02 16:43 UTC, MuhammedZakir commented
Both tekezo's and your modifications use same variable, `simple_vi_mode`. Although I think no one will use 2 different "vi mode" at the same time, it is probably better to use a different variable.

Also, "extra description" file type is HTML, whereas yours is plain text file. In case if you have any difficulty, I can help you on that. :-) Can you please tell what's different in your modifications compared to tekezo's? That wasn't clear from your description.

2020-11-03 03:32 UTC, rationality6 commented
Thank you for the advice!

Let me know if there is I need to do more! anytime.

Thank you!.

2020-11-03 13:54 UTC, MuhammedZakir commented
I gave a quick look at your modification and I found that combinations given in description is slightly wrong. As you have set `key_down_order` to `strict`, shouldn't `s` be pressed first in the `from.simultaneous` sequence rather than after `command/option` and `shift + command/option`? That is,

* `command/option + s + h/j/k/l` ->  `s + command/option + h/j/k/l`
* `shift+command/option + s + h/j/k/l` -> `s + shift+command/option + h/j/k/l`

https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/from/simultaneous-options/#key_down_order

2020-11-03 13:55 UTC, MuhammedZakir requested changes

2020-11-03 13:55 UTC, MuhammedZakir commented on public/extra_descriptions/simvi.html
> +</div>
Corrected HTML tags. Normally, you should use `p` for paragraphs.

```suggestion
<link rel="stylesheet" href="../../vendor/css/bootstrap.min.css" />

<p style="margin-top: 20px; font-weight: bold">
  simvi - simple vi mode
</p>

<p>from tekezo's vi, dosen't work with mac os's combination move keys</p>
<p>so I added keysets like below</p>
<p>for work with mac os's combination keys</p>

<ul>
  <li>option + s + h,j,k,l</li>
  <li>shift + option + s + h,j,k,l</li>
  <li>command + s + h,j,k,l</li>
  <li>shift + command + s + h,j,k,l</li>
</ul>

<p>highly recommended to vi + mac combination keys lover users</p>
```

2020-11-05 17:47 UTC, MuhammedZakir requested changes

2020-11-05 17:47 UTC, MuhammedZakir commented on public/extra_descriptions/simvi.html
> +  <li>shift + command + s + h,j,k,l</li>
```suggestion
  <li>option + s + h,j,k,l</li>
  <li>shift + option + s + h,j,k,l</li>
  <li>command + s + h,j,k,l</li>
  <li>shift + command + s + h,j,k,l</li>
```

@rationality6 In case you have missed my question, I was asking about these. Shouldn't `s` be pressed first (before other keys)?

2020-11-06 11:10 UTC, rationality6 commented on public/extra_descriptions/simvi.html
> +  <li>shift + command + s + h,j,k,l</li>
@MuhammedZakir The ordering doesn't matter. both ways works fine!

2020-11-06 12:26 UTC, merged

2020-11-06 12:29 UTC, MuhammedZakir commented
Added your modification! :+1: :smile: