Add a rule to swap alt/option with command
pqrs-org/KE-complex_modifications pull request #803
Opened 2021-01-16 08:05 UTC by victorporof

Signed-off-by: Victor Porof <victor.porof@gmail.com>

2021-01-16 15:15 UTC, MuhammedZakir requested changes

2021-01-16 15:15 UTC, MuhammedZakir commented on public/json/swap_alt_with_command.json
> +  "title": "Windows Keyboard on Mac"
Please put title at the top. :-)

2021-01-17 09:34 UTC, victorporof commented on public/json/swap_alt_with_command.json
> +  "title": "Windows Keyboard on Mac"
Done.

2021-01-17 12:03 UTC, merged

2021-01-17 12:04 UTC, MuhammedZakir commented
Merged. :-)