Add binding for '⌥ +Tab' to '⌘ +Tab'
pqrs-org/KE-complex_modifications pull request #908
Opened 2021-08-07 06:58 UTC by rustycl0ck

2021-08-07 12:03 UTC, MuhammedZakir commented
As yours is pure json, there is no need for `.erb` file. Also, use `left_command` in place of `left_gui`.

2021-08-07 22:59 UTC, rustycl0ck commented
Thanks for the comments. I have removed the `.erb` file and switched from `left_gui` to `left_command`. Also added an extra description file.

2021-08-08 05:58 UTC, MuhammedZakir commented on public/json/option-tab_to_command-tab.json
> +              "lazy": true
```suggestion
              ]
```

AFAIK, `to.lazy` only works if `from.keycode` is a modifier key.

From https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/to/lazy/:
> If `to.lazy` is `true` and `to.key_code` is modifier flag such as `"key_code": "left_shift"`, the `to.key_code` acts as lazy modifier.

2021-08-08 06:00 UTC, MuhammedZakir requested changes

2021-08-08 06:00 UTC, MuhammedZakir commented on public/extra_descriptions/option-tab_to_command-tab.json.html
> +Use '⌥+Tab' to cycle through applications (in addition to the default '⌘+Tab')
```suggestion
<link rel="stylesheet" href="../../vendor/css/bootstrap.min.css" />

<p>Use '⌥+Tab' to cycle through applications (in addition to the default '⌘+Tab')</p>
```

2021-08-08 06:01 UTC, MuhammedZakir commented
I will merge this once those two are solved. Thanks! :-)

2021-08-08 07:42 UTC, rustycl0ck commented on public/json/option-tab_to_command-tab.json
> +              "lazy": true
Thanks for pointing this out. I didn't fully understand the function of `lazy`. I have removed it now.

2021-08-08 07:42 UTC, rustycl0ck commented on public/extra_descriptions/option-tab_to_command-tab.json.html
> +Use '⌥+Tab' to cycle through applications (in addition to the default '⌘+Tab')
Thanks for suggesting this. I have updated it as requested.

2021-08-08 15:48 UTC, merged

2021-08-08 15:48 UTC, MuhammedZakir commented
Merged. :-)