change rules: emacs like key binds only for Obsidian.app, at vim-insert mode (rev02)
pqrs-org/KE-complex_modifications pull request #939
Opened 2021-09-13 13:33 UTC by hnsol

Deleted `"optional":  "any"` in modifiers,
to avoid working when users press anything other than the control key.

2021-09-13 15:10 UTC, MuhammedZakir requested changes

2021-09-13 15:10 UTC, MuhammedZakir commented on public/json/obsidian_emacs_vim-insert.json
> +              "optional": []
Empty fields are not needed. You can remove them.

2021-09-14 03:18 UTC, hnsol commented on public/json/obsidian_emacs_vim-insert.json
> +              "optional": []
Thank you for your review and comments. I fixed them.

2021-09-14 05:53 UTC, merged

2021-09-14 05:55 UTC, MuhammedZakir commented
Merged. :-)